"""Cyclic group Z_6 shown as a clock diagram on a circle.

Three layers of structure:
  Blue arcs   -- generator [1] stepping through all 6 elements (order 6)
  Orange tri  -- subgroup generated by [2] (order 3): 0->2->4->0
  Green diam  -- subgroup generated by [3] (order 2): 0<->3

Run with: uv run python src/math_paper/cyclic_group_circle.py
"""

from __future__ import annotations

from dataclasses import replace
from pathlib import Path
import sys

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from _viz.output import Presets

SPEC = replace(Presets.SVG_MATH, figsize=(7, 8.2), transparent=False)
OUT_DIR = Path(__file__).resolve().parent.parent.parent / "output"

BLU = "#2A6FDB"
ORG = "#E8862E"
GRN = "#3E9B4F"
AXC = "#333333"
CIRC = "#cccccc"

R = 3.0


def arrowhead(ax, tip, direction, s=0.18, color="k"):
    """Draw a filled triangular arrowhead."""
    dx, dy = direction
    nx, ny = -dy, dx                       # 90 deg CCW
    ax.fill(
        [tip[0], tip[0] - s * dx + s * 0.45 * nx,
         tip[0] - s * dx - s * 0.45 * nx],
        [tip[1], tip[1] - s * dy + s * 0.45 * ny,
         tip[1] - s * dy - s * 0.45 * ny],
        color=color, zorder=5)


def build_figure():
    fig = SPEC.figure()
    ax = fig.add_subplot(111)

    # -- six element positions (clockwise from top) ---------------------- #
    angles = [np.pi / 2 - i * np.pi / 3 for i in range(6)]
    pos = [(R * np.cos(a), R * np.sin(a)) for a in angles]

    # -- main circle (light grey) ---------------------------------------- #
    th = np.linspace(0, 2 * np.pi, 300)
    ax.plot(R * np.cos(th), R * np.sin(th), color=CIRC, lw=1.2, zorder=1)

    # -- Layer 1: blue arc arrows (generator [1], order 6) --------------- #
    for i in range(6):
        a_start = angles[i]
        a_end = angles[(i + 1) % 6]
        if a_end >= a_start:
            a_end -= 2 * np.pi
        t_arc = np.linspace(a_start, a_end, 40)
        ax.plot(R * np.cos(t_arc), R * np.sin(t_arc),
                color=BLU, lw=2.0, zorder=3)
        # arrowhead at end, tangent clockwise
        tip = pos[(i + 1) % 6]
        tang = (-np.sin(a_end), np.cos(a_end))
        arrowhead(ax, tip, tang, s=0.18, color=BLU)

    # -- Layer 2: orange triangle ([2] subgroup, order 3) ---------------- #
    tri_edges = [(0, 2), (2, 4), (4, 0)]
    for i, j in tri_edges:
        ax.plot([pos[i][0], pos[j][0]], [pos[i][1], pos[j][1]],
                color=ORG, lw=2.2, zorder=3)
        mid = ((pos[i][0] + pos[j][0]) / 2,
               (pos[i][1] + pos[j][1]) / 2)
        d = (pos[j][0] - pos[i][0], pos[j][1] - pos[i][1])
        length = np.hypot(*d)
        d_norm = (d[0] / length, d[1] / length)
        arrowhead(ax, mid, d_norm, s=0.22, color=ORG)

    # -- Layer 3: green diameter ([3] subgroup, order 2) ----------------- #
    ax.plot([pos[0][0], pos[3][0]], [pos[0][1], pos[3][1]],
            color=GRN, lw=2.5, zorder=3)
    arrowhead(ax, pos[0], (0, 1), s=0.22, color=GRN)
    arrowhead(ax, pos[3], (0, -1), s=0.22, color=GRN)

    # -- element dots ---------------------------------------------------- #
    for p in pos:
        ax.plot(*p, "ko", ms=8, zorder=5)

    # -- element labels (outside circle) --------------------------------- #
    for i, a in enumerate(angles):
        lr = R + 0.5
        ax.text(lr * np.cos(a), lr * np.sin(a), f"[{i}]",
                fontsize=12, ha="center", va="center",
                fontweight="bold", color=AXC, zorder=6)

    # -- center label ---------------------------------------------------- #
    ax.text(0, 0, r"$Z_6$", fontsize=18, ha="center", va="center",
            fontweight="bold", color=AXC, zorder=6)

    # -- legend (below circle) ------------------------------------------- #
    ly = -4.2

    # item 1: blue arc
    t_l = np.linspace(np.pi / 3, 0, 30)
    ax.plot(0.55 * np.cos(t_l), -4.2 + 0.35 * np.sin(t_l),
            color=BLU, lw=2)
    ax.text(1.0, ly, "steps of [1] (order 6)",
            fontsize=9, color=BLU, va="center")

    # item 2: orange triangle
    t_t = np.array([np.pi / 2, np.pi / 2 - 2 * np.pi / 3,
                    np.pi / 2 + 2 * np.pi / 3, np.pi / 2])
    ax.plot(0.38 * np.cos(t_t), -4.2 + 0.38 * np.sin(t_t),
            color=ORG, lw=1.8)
    ax.text(3.5, ly, "subgroup of order 3",
            fontsize=9, color=ORG, va="center")

    # item 3: green diameter
    ax.plot([-0.35, 0.35], [ly, ly], color=GRN, lw=2)
    ax.text(5.5, ly, "subgroup of order 2",
            fontsize=9, color=GRN, va="center")

    # -- axes ------------------------------------------------------------ #
    ax.set_xlim(-5, 7)
    ax.set_ylim(-5, 4.5)
    ax.set_aspect("equal")
    ax.axis("off")

    return fig


def main():
    fig = build_figure()
    path = SPEC.save(fig, OUT_DIR / "cyclic-group-circle")
    plt.close(fig)
    print(f"Saved: {path}")


if __name__ == "__main__":
    main()
